### ISSUE TITLE
local variable 'fileName' referenced before assignment

### ISSUE THREAD

**Issue by 4gordi** [tralph3/PSX-Cue-Maker#12]
Hi, i have a problem with this script, when i starting script on windows 10 console with parametres: 
`python CueMaker.py -zgm playstation C:\Users\anonimous\Desktop\123`
I take a message 
`Traceback (most recent call last):
  File "C:\Users\anonimous\Desktop\Cue-Maker-master\CueMaker.py", line 412, in <module>
    generateCue(file)
  File "C:\Users\anonimous\Desktop\Cue-Maker-master\CueMaker.py", line 136, in generateCue
    cuePath = fileDirectory + fileName[0:len(fileName) - 4] + ".cue"
UnboundLocalError: local variable 'fileName' referenced before assignment`

Python 3.10 windows 10

**Comment by tralph3** [comment]
I think I see what happened, could you try again now please? Make sure to re-download the program.

**Comment by 4gordi** [comment]
Now i have a error after creating cue and starting creating m3u:
`Traceback (most recent call last):
  File "C:\Users\anon\Desktop\Cue-Maker-master\CueMaker.py", line 416, in <module>
    createM3u(cueFiles)
  File "C:\Users\anon\Desktop\Cue-Maker-master\CueMaker.py", line 272, in createM3u
    if fileName.lower().find(" (disc") != -1 or fileName.lower().find("_(disc") != -1:
UnboundLocalError: local variable 'fileName' referenced before assignment`

**Comment by 4gordi** [comment]
full log:
`[1;32mExtracting .zip...[0m


[1;32mCreating .cue...[0m

Found file: "[1;33mAce Combat 2 (USA).bin[0m"
[1;31mThis file already has a .cue[0m
--------
Found file: "[1;33mChrono Cross (USA) (Disc 1).bin[0m"
[1;31mThis file already has a .cue[0m
--------
Found file: "[1;33mDisney's 101 Dalmatians II - Patch's London Adventure.bin[0m"
[1;31mThis file already has a .cue[0m
--------

[1;32mCreating .m3u...[0m

Traceback (most recent call last):
  File "C:\Users\anon\Desktop\Cue-Maker-master\CueMaker.py", line 416, in <module>
    createM3u(cueFiles)
  File "C:\Users\anon\Desktop\Cue-Maker-master\CueMaker.py", line 272, in createM3u
    if fileName.lower().find(" (disc") != -1 or fileName.lower().find("_(disc") != -1:
UnboundLocalError: local variable 'fileName' referenced before assignment`

**Comment by 4gordi** [comment]
And how i can update your or creating myself links.cfg and what would be in psx.hash and Sony PlayStation Cue Sheets (redump.org)?

**Comment by tralph3** [comment]
The links.cfg file contains links to a file that has the sha1 hash for all the games on that system. The info was taken from redump.org, and parsed with a string to get it into this format. I don't think I have that script lying around currently, but it shouldn't be too hard to re-create it.

As for the "base", that's just a string that is used as a prefix to create a link to the cue file that needs to be downloaded. So for instance you can have "link.com/playstation/" as a base, and then the program adds "Silent Hill.cue" at the end, then it would be able to download the cue.

As a side note, this system is complete and absolute garbage and I'd like this program to burn in hell. But alas, I can't do that now. String manipulation is error-prone, and this program is full of it... shame.

I'll see what I can do about that error.

**Comment by tralph3** [comment]
I believe it should be fixed now....
