### ISSUE TITLE
Separate revisions of same game cause issues with m3u generation

### ISSUE THREAD

**Issue by birdybro** [tralph3/PSX-Cue-Maker#4]
Another one I just noticed. If there are two revisions in the same run of the script, it generates a single m3u for both revisions.

[Driver 2 (USA)m3u.zip](https://github.com/tralph3/Cue-Maker/files/5258613/Driver.2.USA.m3u.zip)

**Comment by tralph3** [comment]
Thanks for giivng some proper testing to the script. Could you detail a bit more about this one? Were the roms named like the formatting section in the readme stated?

**Comment by birdybro** [comment]
They were named in the Redump style in how it handles revisions:

http://redump.org/disc/7271/
Driver 2 (USA) (Disc 1) (Rev 1).bin
Driver 2 (USA) (Disc 1) (Rev 1).cue

http://redump.org/disc/7272/
Driver 2 (USA) (Disc 2) (Rev 1).bin
Driver 2 (USA) (Disc 2) (Rev 1).cue

http://redump.org/disc/5308/
Driver 2 (USA) (Disc 1).bin
Driver 2 (USA) (Disc 1).cue

http://redump.org/disc/5309/
Driver 2 (USA) (Disc 2).bin
Driver 2 (USA) (Disc 2).cue

From the Redump.org Datfile in Romcenter 4.0.1 for reference as to the redump naming scheme:
![image](https://user-images.githubusercontent.com/16388068/93832070-c6f89b80-fc31-11ea-805c-e36a7bc2acd4.png)

**Comment by birdybro** [comment]
Also, no problem as to testing, I am just trying to create a better way of handling multi-disc games as a standard, and you are saving me a ton of time with your script :P

**Comment by tralph3** [comment]
This one is fixed now too, I'll get to making a new release (although those are for linux only, since I'm too lazy to set up a windows vm to compile this into an exe). You can get the changes from the source code tho.
