### ISSUE TITLE
Potential issue: zip needed a "bump" in shell to continue to next step

### ISSUE THREAD

**Issue by birdybro** [tralph3/PSX-Cue-Maker#6]
Just woke up and saw you added zip functionality already! Amazing! 

So I tested the new zip functionality and am reporting a potential issue as a result.

When zipping Juggernaut (USA)
http://redump.org/disc/19173/
http://redump.org/disc/19161/
http://redump.org/disc/19163/

using the command:

`python cuemaker.py -zmr playstation "Sony PSX"`

Juggernaut got stuck at the zipping stage and I had to make the shell window active and press enter to continue. Not sure if that's a side effect of using python or some bug inherent to windows 10 shell's in general (the windows powershell-based package manager Chocolatey has the same issue for some packages), but it got stuck on the step to delete the folder from what I could tell. After pressing enter, it continued, and then it worked on the remaining folders; Koudelka (USA), Legend of Dragoon, The (USA), Lunar - Silver Star Story Complete (USA), and Lunar 2 - Eternal Blue Complete (USA), Metal Gear Solid (USA), Metal Gear Solid (USA) (Rev1) without a bump needed.

What I saw where it was stuck for a long time:

```
←[1;32mCompressing and deleting temporary folders...←[0m

Compressing files in "←[1;33mJuggernaut (USA)←[0m"...
```

I then had to press enter and immediately this appeared:

`Deleting "←[1;33mJuggernaut (USA)←[0m"...`

**Comment by tralph3** [comment]
Hmm take into account that zipping them can take a long time sometimes, depending on your CPU and the size of the files. It took me almost a minute for the larger ones. Make sure it's not just doing it's thing. You can try to see if the zip is increasing in size, if it is, then it's working.

**Comment by birdybro** [comment]
It was like 10 minutes :P 

i7-4790k and being zipped on a samsung 970 evo pcie SSD. It's probably just a bug with windows shell.

**Comment by tralph3** [comment]
Probably, since it reached that part of the script, that's all in the hands of the zipfile module. I really can't do anything with that. I tested it on my machine and it never got stuck. You may want to try Cygwin, it's like a unix shell for Windows.

**Comment by birdybro** [comment]
Found the likely reason FYI.

https://bugs.python.org/issue1602

Looks like the print() function gets hung in Windows, possibly related to Unicode text? Maybe if I ran the batch file in powershell it would handle it better... Interesting!

**Comment by tralph3** [comment]
Well that says it's fixed... and it's from 2007 too... so idk.

**Comment by birdybro** [comment]
It wasn't fixed, I found that from another thread where they were still having a problem. It's an issue inherent to windows shells, so microsoft strikes again! :)

**Comment by tralph3** [comment]
Damn
